# Generated by Django 5.0.4 on 2024-05-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkki', models.CharField(default='auto', max_length=50)),
                ('malli', models.CharField(default='auto', max_length=50)),
                ('vuosi', models.CharField(default='auto', max_length=4)),
                ('väri', models.CharField(default='auto', max_length=20)),
                ('moottori', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('hinta', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Osat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuotenimi', models.CharField(default='varaosat', max_length=50)),
                ('paino', models.CharField(default='varaosat', max_length=20)),
                ('määrä', models.CharField(default='varaosat', max_length=50)),
                ('hinta', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.autot')),
            ],
        ),
    ]
